spring.application.name=auth-service
server.port=${PORT:8081}

spring.datasource.url=${AUTH_DATASOURCE_URL}
spring.datasource.username=${AUTH_DATASOURCE_USERNAME}
spring.datasource.password=${AUTH_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET:clave_super_secreta_para_jwt_2026_proyecto}
jwt.expiration=86400000